config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/hide', to: 'hide#start'
  get '/hide/i', to: 'hide#new'
  post '/hide/i', to: 'hide#new'
  #get '/hide/i/destroy', to: 'hide#destroy'
  get '/hide/i/encode', to: 'hide#encode'
  
  get '/seek', to: 'seek#start'
  get '/seek/i', to: 'seek#new'
  post '/seek/i', to: 'seek#new'
  get '/seek/i/decode', to: 'seek#decode'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hide.rb
class Hide < ApplicationRecord
  #include ActiveModel::Validations
  has_one_attached :cover_image
  #validates_with ValidCover
  has_one_attached :message
  has_one_attached :stego_result
end

app/models/seek.rb
class Seek < ApplicationRecord
  has_one_attached :stego
  has_one_attached :message
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/crypto.rb
require 'openssl'

class Crypt
  def self.enc file, pass, salt
    mess = OpenSSL::Cipher.new('aes-256-cbc')
    mess.encrypt
    mess.pkcs5_keyivgen pass, salt
    encrypted = mess.update File.binread(file)
    encrypted << mess.final
    File.binwrite file, encrypted
  end
  def self.dec file, pass, salt
    mess = OpenSSL::Cipher.new('aes-256-cbc')
    mess.decrypt
    mess.pkcs5_keyivgen pass, salt
    decrypted = mess.update File.binread(file)
    decrypted << mess.final
    File.binwrite file, decrypted
  end
end

app/controllers/hide_controller.rb
require 'pry'
require_relative './lsbStego.rb'
require_relative './crypto.rb'

class HideController < ApplicationController
  #include ActiveStorage::Downloading
  def start
    Hide.delete_all
    @hide = Hide.create(params.permit(:cover_image, :message))
    session[:current_id] = @hide.id
    redirect_to hide_i_path
  end
  
  def new
    @hide = Hide.find(session[:current_id])
    #binding.pry
    if params[:cover_image]
      tempfile = params[:cover_image].tempfile
      if ALLOWED_TYPES.include?(params[:cover_image].content_type)
        @hide.cover_image.attach(io: tempfile, filename: params[:cover_image].original_filename)
      end
      im = MiniMagick::Image.open(tempfile.path)
      @hide.message_cap = (im.width * im.height*2)/8
      im=nil
    end
    if params[:message]
      if params[:message].tempfile.size < (@hide.message_cap - 10)
        if !params[:pass].empty?
          salt = params[:message].tempfile.size.to_s
          Crypt.enc params[:message].tempfile, params[:pass], '81889817'
          @hide.message.attach(io: params[:message].tempfile, filename: params[:message].original_filename)
        else
          @hide.message.attach(io: params[:message].tempfile, filename: params[:message].original_filename)
        end
      end
    end
    @hide.save
    #binding.pry
  end
  
  def destroy
    Hide.delete_all
    reset_session
  end
  
  def encode
    @hide = Hide.find(session[:current_id])
    im = Stego.new(@hide.cover_image.download)
    file_name = ''
    file_name = im.encode(@hide.message.download, "stegout")
    @hide.stego_result.attach(io: File.open(file_name), filename: file_name)
    @hide.save
  end
  private
  ALLOWED_TYPES = ["image/png",
                   "image/gif",
                   "image/jpg",
                   "image/jpeg",
                   "image/bmp"]
  
end

app/controllers/lsbStego.rb
#!/usr/bin/env ruby

require 'pry'
require 'benchmark'
class Integer
  #takes out the last 2 bits of numbers
  def stego_decode
    self.to_s(2).bin_pad8[-2..-1] #last 2 characters
  end
  
  def bin_sub2 bits
    raise ArgumentError if self>255
    pixel = self
    res = pixel.to_s(2).chop.chop
    return (res+=bits).to_i 2
  end
end

class String
  def bin_pad8
    raise ArgumentError,'binary string expected' unless self =~ /\A[10]+\z/
    self.prepend('0'*(8-self.size))
  end
end
class Stego #Base class
  #require 'rmagick'
  require 'mini_magick'
  STEGO_HEADER_SIZE = 4 #A2 encryption if used(ya,no), V size of message, A4 ext
  def initialize file #initializes with cover image
    @cover_image = MiniMagick::Image.read(file)
    @cover_capacity = ((@cover_image.get_pixels.flatten.size)*2)/8
  end
  
  def encode message_file, stego_file_name #initializes the secret message
    if message_file.size > @cover_capacity - STEGO_HEADER_SIZE - 32 #for cipher
      raise ArgumentError, 'Message too big for given cover'
    end
    @message = message_file.unpack('B*').first
    @message_size = message_file.size
    mes_bit_str = StringIO.new(@message.prepend(stego_header))
    #binding.pry
    pixels = @cover_image.get_pixels.flatten
    pixels.map! do |pixel|
      break if (bits = mes_bit_str.read(2)).nil?
      pixel = pixel.bin_sub2 bits
    end
    write stego_file_name, pixels
  end
  
  def write stego_file_name, pixels #writes the pixels into an image
    
    type = @cover_image.type.downcase
    type = (type=='JPEG') ? 'BMP' : type
    final = MiniMagick::Image.import_pixels(pixels.pack('c*'), @cover_image.width, @cover_image.height, @cover_image.data["depth"], "rgb", type)
    res_filename = stego_file_name+"."+type
    final.write res_filename
    return res_filename
  end
  
  def decode stego_file_name
    bit_str = ''
    pixels=@cover_image.get_pixels.flatten
    header_pix_size = STEGO_HEADER_SIZE * 4
    header_bit_str = StringIO.new(pixels.shift(header_pix_size).map(&:stego_decode).join)
    #encryption = [header_bit_str.read(16)].pack('B*')
    message_size = [header_bit_str.read(32)].pack('B*').unpack('V').first
    #ext = [header_bit_str.read(32)].pack('B*')
    #binding.pry
    (0...(message_size*4)).each do |ind|
      bit_str << pixels[ind].stego_decode
    end
    file_name = stego_file_name
    File.open(file_name,'wb') do |file|
      file << [bit_str].pack('B*')
    end
    return file_name
  end
  def decode_header
    bit_str = ''
    pixels = @cover_image.get_pixels.flatten
    header_pix_size = STEGO_HEADER_SIZE * 4
    header_bit_str = StringIO.new(pixels.shift(header_pix_size).map(&:stego_decode).join)
    #enc = [header_bit_str.read(16)].pack('B*')
    messize = [header_bit_str.read(32)].pack('B*').unpack('V').first
    #ext = [header_bit_str.read(32)].pack('B*')
    return messize
  end
  
  private
  def stego_header
    [ @message_size].pack('V').unpack('B*').first
  end
  def bin_sub2 pix_byte, bit2
    return pix_byte  if bit2.nil?
    bit_string = pix_byte.to_s(2).bin_pad8
    ((bit_string.chop.chop) + bit2).to_i 2
  end
  def format_bmp3 pixels
    pixels.each_slice(3).map{|x|x.reverse}.each_slice(@cover_image.width).to_a.reverse
  end
end

app/controllers/seek_controller.rb
require_relative "./lsbStego.rb"
require_relative "./crypto.rb"
class SeekController < ApplicationController
  $pass = ''
  def start
    Seek.delete_all
    @seek = Seek.create(params.permit(:stego))
    session[:current_id]=@seek.id
    redirect_to seek_i_path
  end
  def new
    @seek = Seek.find(session[:current_id])
    if params[:stego]
      tempfile = params[:stego].tempfile
      if ALLOWED_TYPES.include?(params[:stego].content_type)
        @seek.stego.attach(io: tempfile, filename: params[:stego].original_filename)
      end
      messize = Stego.new(@seek.stego.download).decode_header
      if params[:pass]
      $pass = params[:pass]
      end
      @seek.messize = messize
      #binding.pry
    end
    @seek.save
  end
  
  def decode
    @seek = Seek.find(session[:current_id])
    im = Stego.new(@seek.stego.download)
    file_name = im.decode 'resout'
    file = File.open file_name
    #binding.pry
    if !$pass.empty?
      file = File.open file_name
      salt = file.size.to_s
      Crypt.dec file, $pass, '81889817'
      @seek.message.attach(io: file,filename: file_name)
    else
      @seek.message.attach(io: file,filename: file_name)
    end
    @seek.save
  end
  private
  ALLOWED_TYPES = ["image/png",
                   "image/gif",
                   "image/jpg",
                   "image/jpeg",
                   "image/bmp"]
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hide_helper.rb
module HideHelper
end

app/helpers/seek_helper.rb
module SeekHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/hide/encode.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>

</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-lightest">
<main class="main">
<section class="h-full w-full p-6 overflow-hidden md:flex md:flex-row md:rounded-lg md:shadow-big">
<send-upload-area class="flex flex-col items-center justify-center border-2 border-dashed border-grey rounded px-6 py-16 h-full w-full">

<% if @hide.stego_result.attached? %>
<h2 class="font-sans font-bold justify-center"> Hey there, 
<br/>Your encoded image is ready for download</h2>
<label class="btn rounded-lg overflow-hidden p-4 items-center m-8">
<%= link_to ' Download ', rails_blob_path(@hide.stego_result)%>
</label>
<p class="center font-medium text-sm text-blue-dark hover:text-blue-darker focus:text-blue-darker mt-4 mb-2">The browser may render the image, </br>
Try saving it manually</p>
<% else %>
<h2 class="font-sans font-bold justify-center"> Oops, Something went wrong!! 
</h2>
<% end %>
</send-upload-area>
</section>
</main>
</body>
</html>

app/views/hide/new.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>

</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-lightest">
<main class="main">
<section class="h-full w-full p-6 overflow-hidden md:flex md:flex-row md:rounded-lg md:shadow-big">
<div class="px-2 w-full md:px-0 md:mr-6 md:w-1/2">
<send-upload-area class="flex flex-col items-center justify-center border-2 border-dashed border-grey rounded px-6 py-16 h-full w-full">
<% ActiveStorage.variable_content_types[5] = 'image/bmp' %>
<% if @hide.cover_image.attached? %>
<div class="md:shadow-big">
<%= image_tag @hide.cover_image.variant(resize: '200x200'),data: {class: "w-full" } %></div>
<% else %>
<h4> no cover image </h4>
<% end %>
<% if @hide.message.attached? %>
<h4>Message attached</h4> <br/>
<% else %>
<h4> no message sorry </h4>
<% end %>
<%= form_tag({action: :new}, multipart: true) do %>
<% unless @hide.cover_image.attached? %>
<label class="btn rounded-lg overflow-hidden items-center mt-2">

<%= file_field_tag 'cover_image'%><br/></label>
<% else %>
<label class="btn rounded-lg overflow-hidden items-center mt-4">

<%=file_field_tag 'message' %></label>
<% end %></send-upload-area></div>
<div class="px-2 w-4 md:px-0 md:w-1/2">

<% if @hide.cover_image.attached? && !@hide.message.attached? %>
<div class="popup my-12 md:shadow-big" onclick="myFunction()">
  <%= label_tag(:pass,"Password : ") %>
  <%= password_field_tag(:pass) %>
  <span class="popuptext" id="myPopup">Enter password to encrypt</span>
</div>
<br>
<% end %>

<label class="btn rounded-lg overflow-hidden items-center mt-4">
<%= submit_tag %>
</label>
<% end %>
<% if @hide.cover_image.attached? && @hide.message.attached? %>
<label class="btn rounded-lg overflow-hidden p-4 items-center m-6">
<%= link_to 'Encode', hide_i_encode_path%>
</label>
<% end %>
</div>
<div class="mt-6 w-full md:w-1/2 md:-m-2">
<send-intro class="flex flex-col items-center justify-center bg-white px-6 md:py-0 py-6 mb-0 h-full w-full">
<div class="mt-12 flex flex-col h-full">
<h1 class="font-bold">Hide & Seek</h1>
<p class="max-w-sm leading-normal mt-6 md:mt-2 md:pr-16">Hide & Seek lets you hide & retrieve any data in an image, potentially hiding its existence. It uses a simple method known as LSB(Least Significant Bit) Substitution method.</p><!--<img src="" class="intro">--></div></send-intro>
</div>
</section>
</main>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/seek/decode.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>

</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-lightest">
<main class="main">
<section class="h-full w-full p-6 overflow-hidden md:flex md:flex-row md:rounded-lg md:shadow-big">
<send-upload-area class="flex flex-col items-center justify-center border-2 border-dashed border-grey rounded px-6 py-16 h-full w-full">>
<% if @seek.message.attached? %>
<h2 class="font-sans font-bold justify-center"> Hey there, 
<br/>Your decoded message is ready for download</h2>
<label class="btn rounded-lg overflow-hidden p-4 items-center m-8">
<%= link_to 'Download', rails_blob_path(@seek.message)%></label>
<% else %>
<h2 class="font-sans font-bold justify-center"> Oops, Something went wrong!! 
</h2>
<% end %>
</send-upload-area>
</section>
</main>
</body>
</html>

app/views/seek/new.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>

</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-lightest">
<main class="main">
<section class="h-full w-full p-6 overflow-hidden md:flex md:flex-row md:rounded-lg md:shadow-big">
<div class="px-2 w-full md:px-0 md:mr-6 md:w-1/2">
<send-upload-area class="flex flex-col items-center justify-center border-2 border-dashed border-grey rounded px-6 py-16 h-full w-full">
<% if @seek.stego.attached? %>
<% ActiveStorage.variable_content_types[5] = 'image/bmp' %>
<div class="md:shadow-big">
<%= image_tag @seek.stego.variant(resize: '500x500'),data: {class: "w-full md:shadow-big" } %></div>
<label class="btn rounded-lg overflow-hidden p-4 items-center m-6">
<%= link_to 'Decode', seek_i_decode_path %>
</label></div>
<% else %>
<%= form_tag({action: :new}, multipart: true) do %>
<label class="btn rounded-lg overflow-hidden items-center mt-4">
<%= file_field_tag 'stego' %></label></send-upload-area></div>
<div class="px-2 w-4 md:px-0 md:w-1/2">


<div class="popup my-12 md:shadow-big" onclick="myFunction()">
  <%= label_tag(:pass,"Password : ") %>
  <%= password_field_tag(:pass) %>
  <span class="popuptext" id="myPopup">This file may require password</span>
</div>
<br>


<label class="btn rounded-lg overflow-hidden p-4 items-center m-6">
<%= submit_tag %></label>
</div>
<% end %>
<% end %>


<send-intro class="flex flex-col items-center justify-center bg-white px-6 md:py-0 py-6 mb-0 h-full w-full">
<div class="mt-12 flex flex-col h-full">
<h1 class="font-bold">Hide & Seek</h1>
<p class="max-w-sm leading-normal mt-6 md:mt-2 md:pr-16">Hide & Seek lets you hide & retrieve any data in an image, potentially hiding its existence. It uses a simple method known as LSB(Least Significant Bit) Substitution method.</p><!--<img src="" class="intro">--></div></send-intro>
</div>

</section>
</main>
</body>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html lang="en-US">
<head>

</head>
<body class="flex flex-col items-center font-sans md:h-screen md:bg-grey-lightest">
<main class="main">
<section class="h-full w-full p-6 overflow-hidden md:flex md:flex-row md:rounded-lg md:shadow-big">
<div class="px-2 w-full md:px-0 md:mr-6 md:w-1/2">
<a class="flex flex-col items-center justify-center border-2  rounded px-6 py-16 h-full w-full hover:bg-blue hover:text-white text-lg border-dashed border-grey" href="/hide">
Hide </a>
</div>
<div class="px-2 w-full md:px-0 md:mr-6 md:w-1/2">
<a class="flex flex-col items-center justify-center border-2  border-dashed border-grey rounded px-6 py-16 h-full w-full hover:bg-blue hover:text-white text-lg" href="/seek">
Seek </a>
</div>